lint:
  stage: test
  image: eclipse-temurin:17-jdk
  before_script:
    - cd car4u
  script:
    - ./gradlew detekt
  except:
    - schedules

test:
  stage: test
  image: eclipse-temurin:17-jdk
  before_script:
    - cd car4u
  script:
    - ./gradlew test
  except:
    - schedules

notify_v2:
  stage: notify
  image: eclipse-temurin:17-jdk
  before_script:
    - mv scraper/$SCRAPE_OUTPUT_FILENAME car4u/
    - cd car4u
  script:
    - cat $SCRAPE_OUTPUT_FILENAME | ./gradlew run --no-daemon
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
