default:
  image: eclipse-temurin:17-jdk

stages:
  - test
  - run

lint:
  stage: test
  script:
    - ./gradlew -q --continue detektMain detektTest
  except:
    - schedules

test:
  stage: test
  script:
    - ./gradlew -q test
  except:
    - schedules

notify_v2:
  stage: run
  script:
    - ./gradlew -q --no-daemon run
  only:
    - schedules
  timeout: 5m
