stages:
  - validate
  - scrape
  - notify

variables:
  SCRAPE_OUTPUT_FILENAME: status.json

validate_schedule:
  stage: validate
  image: ruby:3.2-bullseye
  before_script:
    - cd validator
    - bundle install
  script:
    - ruby validate.rb
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

puppeteer:
  stage: scrape
  image: node:18-bullseye
  before_script:
    - apt-get update && apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2
    - cd scraper
  script:
    - npm ci
    - echo "Running scraper for booking times $BOOKING_TIMES"
    - node index.js "$BOOKING_TIMES" > $SCRAPE_OUTPUT_FILENAME
  artifacts:
    paths:
      - scraper/*.png
      - scraper/$SCRAPE_OUTPUT_FILENAME
    when: always
  retry:
    max: 2
    when: script_failure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

notify-if-available:
  stage: notify
  image: golang:1.20-bullseye
  before_script:
    - mv scraper/$SCRAPE_OUTPUT_FILENAME notifier/
    - cd notifier
  script:
    - go run . < $SCRAPE_OUTPUT_FILENAME
  needs:
    - puppeteer
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
