default:
  image: eclipse-temurin:17-jdk

stages:
  - test
  - run

lint:
  stage: test
  script:
    - ./gradlew -q --continue detektMain detektTest
  except:
    - schedules

test:
  stage: test
  script:
    - ./gradlew -q test
  except:
    - schedules

notify:
  stage: run
  image: mcr.microsoft.com/playwright/java:v1.40.0-jammy
  script:
    - ./gradlew -q --no-daemon run
  artifacts:
    paths:
      - availability_page.png
  only:
    - schedules
  timeout: 5m
